spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ag_demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
